# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-15 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Mnemonic', models.CharField(max_length=3)),
                ('ExchangeRate', models.FloatField()),
                ('LesserPlaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Currencies')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('IsPercent', models.NullBooleanField()),
                ('PercentValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_created=True)),
                ('Number', models.BigIntegerField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Currencies')),
                ('MethodOfDelivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.DeliveryType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPositions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=500)),
                ('Image', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('SetImplicitly', models.BooleanField()),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Currencies')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='orderpositions',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AddField(
            model_name='deliverypricelist',
            name='DeliveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.DeliveryType'),
        ),
    ]
