# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-16 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181015_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypricelist',
            name='Currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Currencies'),
        ),
        migrations.AlterField(
            model_name='deliverypricelist',
            name='DeliveryMethod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.DeliveryType'),
        ),
    ]
