# Generated by Django 2.1.2 on 2018-10-08 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='UserName',
            field=models.CharField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='AptSuiteNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='Client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='Country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='Name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='PostalCode',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='Street',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='StreetNumber',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
