# Generated by Django 2.1.2 on 2018-10-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181008_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=500)),
                ('Price', models.FloatField(default=0)),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='shop.Currency'),
            preserve_default=False,
        ),
    ]
