# Generated by Django 2.1.2 on 2018-10-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20181008_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryprice',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='orderpositions',
            name='DeliveryType',
        ),
        migrations.AddField(
            model_name='deliveryprice',
            name='DeliveryType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.DeliveryType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpositions',
            name='Currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpositions',
            name='Price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='orderpositions',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
    ]
