# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20181017_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Number',
            new_name='ReferenceNumber',
        ),
        migrations.AlterField(
            model_name='order',
            name='Timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
