# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20181017_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ReferenceNumber',
            field=models.BigIntegerField(null=True),
        ),
    ]
