# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20181017_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylist', to='exchange.Category')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorylist', to='exchange.Product')),
            ],
        ),
    ]
