# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_categorylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylist',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='exchange.Category'),
        ),
    ]
