# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20181017_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ReferenceNumber',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
